root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - jasmine
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'standard'
env:
  jasmine: true
  node: true
